version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y
      - "SA_PASSWORD=GR3@Tpassword"
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5100:5100"
    environment:
      - DJAMBI_Api__apiAddress=http://*:5100
      - DJAMBI_Api__cookieDomain=localhost
      - DJAMBI_Api__webAddress=http://localhost:8080
      - DJAMBI_Log__directory=
      - "DJAMBI_Sql__connectionString=Data Source=db;Initial Catalog=Apex2;User Id=SA;Password=GR3@Tpassword;"
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "8080:8080"