//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Djambi.UI.Resources.Default {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Djambi.UI.Resources.Default.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assassin.
        /// </summary>
        public static string Assassin {
            get {
                return ResourceManager.GetString("Assassin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF663300.
        /// </summary>
        public static string BoardLabelBackgroundColor {
            get {
                return ResourceManager.GetString("BoardLabelBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFC0C0C0.
        /// </summary>
        public static string BoardLabelColor {
            get {
                return ResourceManager.GetString("BoardLabelColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFFFFFF.
        /// </summary>
        public static string CellColor1 {
            get {
                return ResourceManager.GetString("CellColor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF000000.
        /// </summary>
        public static string CellColor2 {
            get {
                return ResourceManager.GetString("CellColor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF808080.
        /// </summary>
        public static string CellColorSeat {
            get {
                return ResourceManager.GetString("CellColorSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief.
        /// </summary>
        public static string Chief {
            get {
                return ResourceManager.GetString("Chief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corpse.
        /// </summary>
        public static string Corpse {
            get {
                return ResourceManager.GetString("Corpse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diplomat.
        /// </summary>
        public static string Diplomat {
            get {
                return ResourceManager.GetString("Diplomat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string ImageDirectory {
            get {
                return ResourceManager.GetString("ImageDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journalist.
        /// </summary>
        public static string Journalist {
            get {
                return ResourceManager.GetString("Journalist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFB22222.
        /// </summary>
        public static string PlayerColor1 {
            get {
                return ResourceManager.GetString("PlayerColor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF228B22.
        /// </summary>
        public static string PlayerColor2 {
            get {
                return ResourceManager.GetString("PlayerColor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF0000CD.
        /// </summary>
        public static string PlayerColor3 {
            get {
                return ResourceManager.GetString("PlayerColor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF800080.
        /// </summary>
        public static string PlayerColor4 {
            get {
                return ResourceManager.GetString("PlayerColor4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF808080.
        /// </summary>
        public static string PlayerColorNeutral {
            get {
                return ResourceManager.GetString("PlayerColorNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Seat.
        /// </summary>
        public static string Seat {
            get {
                return ResourceManager.GetString("Seat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF008000.
        /// </summary>
        public static string SelectionColor {
            get {
                return ResourceManager.GetString("SelectionColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFFFF00.
        /// </summary>
        public static string SelectionOptionColor {
            get {
                return ResourceManager.GetString("SelectionOptionColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Djambi.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thug.
        /// </summary>
        public static string Thug {
            get {
                return ResourceManager.GetString("Thug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undertaker.
        /// </summary>
        public static string Undertaker {
            get {
                return ResourceManager.GetString("Undertaker", resourceCulture);
            }
        }
    }
}
