name: API Deploy

on:
  push:
    branches: [ master ]
    paths:
      - api/**/*
      - .github/workflows/api-deploy.yml

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup ECR
      run: $( aws ecr get-login --no-include-email )

    - name: Build image
      run: docker build -t djambi_api-prod -f api/Dockerfile .

    - name: Tag image
      run: docker tag djambi_api-prod ${{ secrets.AWS_API_ECR_REPOSITORY }}

    - name: Push image
      run: docker push ${{ secrets.AWS_API_ECR_REPOSITORY }}

    - name: Create EB bundle
      # Must use custom delimiter in sed because / will appear in URLs passed in
      run: |
        sed -i 's|{AWS_API_ECR_REPOSITORY}|${{ secrets.AWS_API_ECR_REPOSITORY }}|g' api/Dockerrun.aws.json
        zip -r -j api/eb-bundle.$GITHUB_RUN_ID.zip api/Dockerrun.aws.json

    - name: Upload EB bundle to S3
      run: aws s3 cp api/eb-bundle.$GITHUB_RUN_ID.zip s3://${{ secrets.AWS_API_S3_BUCKET }}

    - name: Create EB app version
      run: aws elasticbeanstalk create-application-version --application-name ${{ secrets.AWS_API_EB_APPLICATION }} --version-label $GITHUB_RUN_ID --source-bundle S3Bucket=${{ secrets.AWS_API_S3_BUCKET }},S3Key=eb-bundle.$GITHUB_RUN_ID.zip

    - name: Update EB environment app version
      run: aws elasticbeanstalk update-environment --application-name ${{ secrets.AWS_API_EB_APPLICATION }} --environment-name ${{ secrets.AWS_API_EB_ENVIRONMENT }} --version-label $GITHUB_RUN_ID
