# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Web Quality Gates

on:
  push:
    branches: [ master ]
    paths:
      - web/**/*
      - .github/workflows/web-quality-gates.yml

  pull_request:
    branches: [ master ]
    paths:
      - web/**/*
      - .github/workflows/web-quality-gates.yml

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci
      working-directory: ./web

    - name: Lint
      run: eslint ./web --ext .ts,.tsx

    - name: Build
      run: npm run build --if-present
      working-directory: ./web

    - name: Test
      run: npm test
      working-directory: ./web
