name: Web2 Quality Gates

on:
  push:
    branches:
      - master
      - develop
      - release/**
    paths:
      - web2/**/*
      - .github/workflows/web2-quality-gates.yml

  pull_request:
    branches:
      - master
      - develop
      - release/**
    paths:
      - web2/**/*
      - .github/workflows/web2-quality-gates.yml

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci
      working-directory: ./web2

    - name: Build
      run: npm run build --if-present
      working-directory: ./web2

    - name: Test
      run: npm test
      working-directory: ./web2
