name: Web2 Deploy

on:
  push:
    branches: [ master ]
    paths:
      - web2/**/*
      - .github/workflows/web2-deploy.yml

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci
      working-directory: ./web2

    - name: Build
      run: npm run build
      working-directory: ./web2

    - name: Update environment config file
      run: sed -i 's|http://localhost:5100|${{ secrets.AWS_API_URL }}|g' build/env.json
        # Must use custom delimiter with sed because paths have /'s
      working-directory: ./web2

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_BUCKET: ${{ secrets.AWS_WEB2_S3_BUCKET }}
        SOURCE_DIR: "web2/build"

    - name: Invalidate CloudFront Cache
      uses: awact/cloudfront-action@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        DISTRIBUTION_ID: ${{ secrets.AWS_WEB2_CLOUDFRONT_DISTRO }}
        SOURCE_PATH: "/*"
