name: Web2 Quality Gates

on:
  push:
    branches:
      - master
      - develop
      - release/**
    paths:
      - web2/**/*
      - api/api.web/**/*
      - .github/workflows/web2-quality-gates.yml
      - utils/generate-swagger-doc.ps1

  pull_request:
    branches:
      - master
      - develop
      - release/**
    paths:
      - web2/**/*
      - api/api.web/**/*
      - .github/workflows/web2-quality-gates.yml
      - utils/generate-swagger-doc.ps1

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Build API
      run: dotnet build -c release
      working-directory: ./api

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '9.0.4' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64

    - name: Generate API client
      run: .\generate-api-client -sourcePath ../api/api.host/bin/release/netcoreapp3.1/openapi.json -outDir ../web2/src/api-client
      working-directory: ./rest-client-generator

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci
      working-directory: ./web2

    - name: Build
      run: npm run build --if-present
      working-directory: ./web2

    - name: Test
      run: npm test
      working-directory: ./web2
